import type { Metadata } from "next";
import "ress";
import "./globals.css";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "えほんポケット",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
